title: Hudanyun Sheng (Dannie)
logo: "/images/photoSquare.jpg"
description:
 Data scientist
 <br><br>
 M.S. in Electrical and Computer Engineering
 <br><br>
 M.S. in Industrial and System Engineering
  <br><br>
 B.S. in Physics
  <br><br>
 <a href="https://www.linkedin.com/in/hudanyunsheng/">View My LinkedIn Profile</a>
theme: jekyll-theme-hacker
