title: Hudanyun Sheng
logo: "/images/photoSquare.jpg"
description: >
  Also known as Dannie
  <br><br>
  Data scientist | Bioinformatics researcher
  <br><br>
  Email: <a href="mailto:hudanyun.sheng@gmail.com">hudanyun.sheng@gmail.com</a>
  <br><br>
  <a href="mailto:hudanyun.sheng@gmail.com">
  <img border="0" alt="Email" src="/images/email.png" width="100" height="100">
  </a>
  Phone: 352-281-3829
  <br><br>
  Twitter: <a href="https://twitter.com/HudanyunSheng">@HudanyunSheng</a>
  <br><br>
  <a href="/pdf/HudanyunSheng_CV.pdf">My CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/hudanyunsheng/">My LinkedIn Profile</a>
footer:
  - label: "mail"
  - icon: "/images/email.png"
  - url: "mailto:hudanyun.sheng@gmail.com"
theme: jekyll-theme-minimal
