title: Hudanyun Sheng
logo: "/images/photoSquare.jpg"
description: >
  Also known as Dannie.
  <br><br>
  Data scientist | Bioinformatics researcher
  <br><br>
  Take a look at my CV
  <a href="/pdf/HudanyunSheng_CV.pdf">here</a>.
  <br><br>
  <a href="https://github.com/DannieSheng">
  <img border="0" alt="My Github Profile: https://github.com/DannieSheng" src="/images/github.png" width="40" height="40"
  </a>
  <a href="https://www.linkedin.com/in/hudanyunsheng/">
  <img border="0" alt="My LinkedIn Profile: https://www.linkedin.com/in/hudanyunsheng/" src="/images/linkedin.png" width="40" height="40"
  </a>
  <a href="https://twitter.com/HudanyunSheng">
  <img border="0" alt="Twitter: @HudanyunSheng" src="/images/twitter.png" width="40 height="40>
  </a>
  <a href="mailto:hudanyun.sheng@gmail.com">
  <img border="0" alt="Email: hudanyun.sheng@gmail.com" src="/images/email.png" width="40" height="40">
  </a>
#  <br><br>
#  Phone: 352-281-3829
#  <br><br>

theme: jekyll-theme-architect
