title: Hudanyun Sheng
logo: "/images/photoSquare.jpg"
description: >
  Also known as Dannie
  Data scientist | Bioinformatics researcher
  <br><br>
  Email: <a href="mailto:hudanyun.sheng@gmail.com">hudanyun.sheng@gmail.com</a>
  <br><br>
  - label: "mail"
  - icon: "/images/email.png"
  - url: "mailto:hudanyun.sheng@gmail.com"
  <br><br>
  Phone: 352-281-3829
  <br><br>
  Twitter: @HudanyunSheng
  <br><br>
  <a href="/pdf/HudanyunSheng_CV.pdf">My CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/hudanyunsheng/">My LinkedIn Profile</a>
theme: jekyll-theme-minimal
