title: Hudanyun Sheng
logo: "/images/photoSquare.jpg"
description: >
  Also known as Dannie
  <br><br>
  Data scientist | Bioinformatics researcher
  <br><br>
  <a href="mailto:hudanyun.sheng@gmail.com">
  <img border="0" alt="Email" src="/images/email.png" width="35" height="35"></a>
  hudanyun.sheng@gmail.com
  <br><br>
  Phone: 352-281-3829
  <br><br>
  <a href="https://twitter.com/HudanyunSheng">
  <img border="0" alt="Twitter" src="/images/twitter.png" width="35 height="35></a>
  @HudanyunSheng
  <br><br>
  <a href="/pdf/HudanyunSheng_CV.pdf">My CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/hudanyunsheng/">My LinkedIn Profile</a>
footer:
  - label: "mail"
  - icon: "/images/email.png"
  - url: "mailto:hudanyun.sheng@gmail.com"
theme: jekyll-theme-minimal
