title: Hudanyun Sheng (Dannie)
logo: "/images/photoSquare.jpg"
description: >
  Data scientist | Bioinformatics researcher in Donald Danforth Plant Science Center
  <br><br>
  Email: hudanyun.sheng@gmail.com
  <br><br>
  Phone: 352-281-3829
  <br><br>
  Twitter: @HudanyunSheng
  <br><br>
  <a href="https://www.linkedin.com/in/hudanyunsheng/">View My LinkedIn Profile</a>
  <a href="/pdf/HudanyunSheng_master_thesis.pdf">Master thesis</a>
theme: jekyll-theme-hacker
